[tool.black]
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '''
/(
  build
| install
| log
| \.venv
| venv
| \.git
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["build", "install", "log", ".venv", "venv", ".git"]

[tool.flake8]
max-line-length = 100
extend-ignore = [
  "E203",  # whitespace before ':' (black-kompatibel)
  "W503"   # line break before binary operator (black-kompatibel)
]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "install",
  "log",
  ".venv",
  "venv"
]
